language: objective-c

xcode_workspace: WeakRefCollections.xcworkspace
xcode_scheme: WeakRefCollections
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3

cache:
  - bundler
  - cocoapods

install:
  - bundle install 
  - pod install

script:
  - set -o pipefail && xcodebuild clean build test -workspace WeakRefCollections.xcworkspace -scheme WeakRefCollections -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=latest' | xcpretty
