language: objective-c

xcode_workspace: WeakRefCollections.xcworkspace
xcode_scheme: WeakRefCollections
osx_image: xcode8.1
xcode_sdk: iphonesimulator10.1

cache:
  - bundler
  - cocoapods

before_install:
  - gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  - rvm get head
  - gem install bundler
  - bundle install
  - pod install

script:
- xcodebuild clean build test -workspace WeakRefCollections.xcworkspace -scheme WeakRefCollections -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
